name: Run JavaScript Examples

on: workflow_dispatch

jobs:
  run-js:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Run JavaScript files in 01_basics
      run: |
        for file in 01_basics/*.js; do
          node "$file"
        done
